### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sakhaswara** [MRHRTZ/Cek-Nomor-Rekening#2]
![Screenshot_2023-12-14-12-43-14-793_com termux](https://github.com/MRHRTZ/Cek-Nomor-Rekening/assets/76629250/200248a3-0942-49ad-b13c-f2474ebd9895)

**Comment by MRHRTZ** [comment]
Project ini langsung hit ke web cekrekening.id yg dimana skrng sudah menggunakan captcha, jadi untuk saat ini belum bisa jalan semestinya.
